# BNF SYNTAX FILE OF BASH FOR LIBEXECTREE
# based upon the BNF file from: http://stackoverflow.com/a/15599860/500942

# deviation from standard BNF:
#	left side non-terminals in capitals mark lexer objects
#	<*> marks expansion (mostly for strings)
#	{} marks a terminal or non-terminal that may be repeated or omitted
<LETTER> ::= a
           | b
           | c
           | d
           | e
           | f
           | g
           | h
           | i
           | j
           | k
           | l
           | m
           | n
           | o
           | p
           | q
           | r
           | s
           | t
           | u
           | v
           | w
           | x
           | y
           | z
           | A
           | B
           | C
           | D
           | E
           | F
           | G
           | H
           | I
           | J
           | K
           | L
           | M
           | N
           | O
           | P
           | Q
           | R
           | S
           | T
           | U
           | V
           | W
           | X
           | Y
           | Z

<DIGIT> ::= 0
          | 1
          | 2
          | 3
          | 4
          | 5
          | 6
          | 7
          | 8
          | 9

<SYMBOL> ::= '!'
           | '@'
           | '#'
           | '$'
           | '%'
           | '^'
           | '&'
           | '*'
           | '('
           | ')'
           | '-'
           | '_'
           | '+'
           | '='
           | '{'
           | '}'
           | '['
           | ']'
           | ':'
           | ';'
           | '"'
           | '<'
           | '>'
           | ','
           | '.'
           | '/'
           | '?'
#		   | '\''
#		   | '\\'

<SPACE> ::= ' '
          | '	'

<NUMBER> ::= <digit>
           | <number> <digit>

<WORD> ::= <letter>
         | <word> <letter>
         | <word> '_'
		 | '\'' {WORD, NUMBER, SPACE, SYMBOL} '\''

<STRING> ::= '"' <*> '"'

<assignment> ::= <word> '=' <word>

<redirection> ::=  '>' <word>
                |  '<' <word>
                |  <number> '>' <word>
                |  <number> '<' <word>
                |  '>>' <word>
                |  <number> '>>' <word>
                |  '<<' <word>
                |  <number> '<<' <word>
                |  '<&' <number>
                |  <number> '<&' <number>
                |  '>&' <number>
                |  <number> '>&' <number>
                |  '<&' <word>
                |  <number> '<&' <word>
                |  '>&' <word>
                |  <number> '>&' <word>
                |  '<<-' <word>
                |  <number> '<<-' <word>
                |  '>&' '-'
                |  <number> '>&' '-'
                |  '<&' '-'
                |  <number> '<&' '-'
                |  '&>' <word>
                |  <number> '<>' <word>
                |  '<>' <word>
                |  '>|' <word>
                |  <number> '>|' <word>

<redirection_list> ::= <redirection>
                     | <redirection_list> <redirection>

<command_element> ::=  <word>
                    |  <assignment>
                    |  <redirection>

<command> ::=  <command_element>
            |  <command> <command_element>

<command_chain> ::= <command> ';'
                  | <command> '|'
				  | <command_chain> <command>
